<?php View::content(); ?>
<div class="span6 offset2">
    <table class="table stripped table-hover table-striped">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Nivel</th>
                <th>Estado</th>
                <th colspan="2" class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($lista as $item): $estado = ($item->estado)?'Activo':'Inactivo';?>
            <tr>
                <td><?php echo $item->usuario; ?></td>
                <td><?php echo ($item->nivel)?$item->nivel:'Administrador'; ?></td>
                <td><?php echo $estado; ?></td>
                <td class="text-center"><?php echo Html::link("usuario/estado/$item->usuario/", '<i class="icon-circle icon-large '.$estado.'" title="Cambiar Estado"></i>'); ?></td>
                <td class="text-center"><?php echo Html::link("usuario/modificar/$item->usuario/", '<i class="icon-edit icon-large verde" title="Modificar"></i>'); ?></td>
                <td class="text-center"><?php echo Html::link("usuario/eliminar/$item->usuario/", '<i class="icon-remove icon-large rojo" title="Eliminar"></i>', 'id="eliminar" data-toggle="modal" data-target="#modalEliminar"'); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php View::partial('modal-eliminar'); ?>