<!-- Modal -->
<div id="modalEliminar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel" aria-hidden="true">
    <div class="modal-header">
        <h3 id="modalEliminarLabel">Confirme...</h3>
    </div>
    <div class="modal-body">
        <p>¿Esta seguro de eliminar este elemento?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <a class="btn btn-danger">Eliminar</a>
    </div>
</div>
<script type="text/javascript">
    var link_action;
    $('.eliminar').click(function(event){
        event.preventDefault();
        $('.btn-danger').attr('href', $(this).attr('href'));
        $('#modalEliminar').modal();
    });
</script>