<!-- Modal -->
<div id="modalConfirmar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel" aria-hidden="true">
    <div class="modal-header">
        <h3 id="modalEliminarLabel">Confirme...</h3>
    </div>
    <div class="modal-body">
        <p>
            ¿Esta seguro de que esta persona voto?<br/>
            Cédula: <span id="cedula_modal"></span><br/>
            Nombre: <span id="nombre_modal"></span><br/>
            Centro Votación: <span id="centro_modal"></span><br/>
        </p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true" id="confirmar">Confirmar</button>
    </div>
</div>
<script type="text/javascript">
    var idResp = 0;
    $('form').on('submit', function(e){
        e.preventDefault();
        var c = $('#cedula').val();
        $.post('<?php echo PUBLIC_PATH; ?>buscar/buscar/',
        {
            cedula: c,
            tipo: 'json'
        },
        function(data) {
            if (data.message == 'OK') {
                idResp = data.id;
                $('.modal-body #cedula_modal').html(data.cedula);
                $('.modal-body #nombre_modal').html(data.nombres+' '+data.apellidos);
                $('.modal-body #centro_modal').html(data.centro_votacion);
                $('#modalConfirmar').modal('show');
            } else {
                alert(data.text);
            }
        },
        'json');
    });

    $('#confirmar').on('click', function(e){
        $.post('<?php echo PUBLIC_PATH; ?>voto/reporte_json/',
        {
            id: idResp,
        },
        function(data) {
            if (data.message == 'OK') {
                alert('Voto cargado con éxito');
            } else {
                alert('No se pudo cargar el voto, intente de nuevo');
            }
        },
        'json');
    });
</script>