


<div class="span10 offset1">

<table class="table table-stripped">
	<thead>
		<tr>
			<th>Centro de Votacion</th>
			<th>Cedula</th>
			<th>Nombre y Apellido</th>
			<th>Telefono</th>
			<th>Celular</th>
			<th>STATUS</th>

		</tr>
	</thead>
	<?php

if($busqueda){
$estado = ($busqueda->estatus)?'Activo':'Inactivo';
print "
	<tbody>
		<tr>
			<td>$busqueda->centro_votacion</td>
			<td>$busqueda->cedula</td>
			<td>$busqueda->nombres   $busqueda->apellidos</td>
			<td>$busqueda->telefono</td>
			<td>$busqueda->celular</td>
 			<td class=\"text-center\">
 				<i class=\"icon-circle icon-large $estado \" title=\"Cambiar Estado\"></i>
 			</td>
		</tr>

	</tbody>
";
}else{

	print "	<tbody>
		<tr>
			<td colspan =  \"6\">esta Vacia</td>


		</tr>

	</tbody>";
}

	?>

</table>

</div>