<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta charset='<?php echo APP_CHARSET ?>' />
  <title>PSUV Falcon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="stylesheet" type="text/css" href="/panel_sala/css/imprimir" media="print">
    <!-- Bootstrap -->
    <?php
    Tag::css('bootstrap/bootstrap');
    Tag::css('bootstrap/bootstrap-responsive');
    Tag::css('font-awesome/font-awesome.min');
    Tag::css('font-awesome/css');
    Tag::css('app');
    echo Html::IncludeCss();
    ?>


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <?php echo Tag::js('html5shiv'); ?>
    <![endif]-->
    <!--[if IE 7]>
        <?php
        echo '<link href="' . PUBLIC_PATH . "css/font-awesome/font-awesome-ie7.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />";
        ?>
    <![endif]-->
    <?php echo Tag::js('bootstrap/jquery'); ?>
    <?php echo Tag::js('bootstrap/bootstrap.min'); ?>
</head>
<body>
<div id="wrap">
<?php View::partial('panel_sala/nav'); ?>

    <div class="container-fluid">
    <div class="row-fluid">

    <div class="span12">
       <?php View::content(); ?>
    </div>

    </div>
    </div>
    <div class=" clearfix"></span>
</div>
<?php View::partial('panel_sala/footer') ?>
</body>
</html>
