


<table class="table stripped table-hover table-striped">
	<thead>
		<tr>
			<th> n°</th>
			<th>Muncipio</th>
			<th>Reporte</th>
			<th>%</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>Acosta</td>
			<td>110</td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td>Bolivar</td>
			<td>80</td>
			<td></td>
		</tr>
		<tr>
			<td>3</td>
			<td>Buchivacoa</td>
			<td>45</td>
			<td></td>
		</tr>
	</tbody>
</table>