<!-- <div class="span6 offset3">

<?php

    //Utils::grid(array('parroquia','listarParroquia',$municipio),TRUE, array('Ver'=>"reporte/centros/$municipio/"));

?>


</div> -->


<div class="span6 offset3">

<?php
$i = 1;
$total = 0;
?>

  <table class="table stripped table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Parroquia</th>
                <th class="text-center">Votos</th>
                <th class="text-center hidden-print">Detalle</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($lista as $item):
            ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $item->parroquia; ?></td>
  				<td class="text-center"><?php echo $item->votos; ?></td>
  				 <td class="text-center hidden-print"> <?php echo Html::link("reporte/centros/$item->mun_id/$item->pq_id", 'Ver Mas' ) ?></td>

            </tr>

            <?php  $i++; $total +=$item->votos; endforeach; ?>
            <tr> 
				<td colspan = "2" ></td>
				<td class="text-center" ><?php echo $total?></td>
				<td class="text-center" ></td>
            	</tr>
        </tbody>
    </table>

</div>