<div class="span6 offset3">

<?php View::content(); ?>

<?php if($lista): //print_r($lista); ?>
    <table class="table stripped table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Código</th>
                <th>Centro</th>
                <th class="text-center">Maduro</th>
                <th class="text-center">Capriles</th>
                <th class="text-center">Reporte</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($lista as $item):
            $indice=($reportes[$item->centro_id])?$reportes[$item->centro_id]:0;
            echo Form::open('', 'post', 'id="'.$item->centro_id.'" data-reporte="'.($indice+1).'"');?>
            <tr>
                <td><?php echo $item->centro_id; ?></td>
                <td><?php echo $item->Codigo; ?></td>
                <td><?php echo $item->Centro; ?></td>
                <td><?php echo Form::text('maduro', 'class="input-mini"'); ?></td>
                <td><?php echo Form::text('capriles', 'class="input-mini"'); ?></td>
                <td class="<?php echo $item->centro_id; ?>"><?php echo Form::submit($text[$indice]->nombre_reporte, 'class="btn btn-primary"'); ?></td>
            </tr>
            </form>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">
        var reportes = new Array('none', <?php echo implode(',', $js_repos); ?>);
        $('form').on('submit', function(e){
            e.preventDefault();
            var campo = $(this).serializeArray();
            var maduro = campo[0].value;
            var capriles = campo[1].value;
            var hora = $(this).attr('data-reporte');
            var centro = $(this).attr('id');
            if (maduro == '' && capriles == '') {
                alert('No se puede reporte vacío');
            } else {
                reportar(hora, centro, maduro, capriles);
            }
        });

        function reportar(hora, centro, maduro, capriles) {
            var reportes = new Array('none', <?php echo implode(',', $js_repos); ?>);
            var nueva_hora;
            if (maduro == ''){
                    maduro = 0;
            }
            if (capriles == ''){
                capriles = 0;
            }
            $.getJSON(
            '<?php echo PUBLIC_PATH; ?>reporte/reportarvoto/'+hora+'/'+centro+'/'+maduro+'/'+capriles,
            null,
            function(data){
                if(data.msg=='OK'){
                    alert('Reporte de Voto exitoso');
                    nueva_hora=parseInt(hora)+1;
                    console.log(reportes[nueva_hora]);
                    console.log($('#'+centro).attr('data-reporte'));
                    $('#'+centro).attr('data-reporte', nueva_hora);
                    $('.'+centro+'>input:submit').val(reportes[nueva_hora]);
                } else {
                    alert('Error reportar vuelva a intentar');
                }
            });
        }
    </script>
<?php endif; ?>
</div>