<div class="container">
    <div class="navbar  navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php echo Html::link('index', 'PSUVFACON','class="brand"'); ?>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">

             <?php echo Html::link('', 'Principal'); ?>
              </li>
              <li class="">

                 <?php echo Html::link('reporte/', 'Reportes'); ?>
              </li>
               <li class="">

                <?php echo Html::link('llamadas/', 'LLamadas'); ?>

              </li>
               <li class="">

                <?php echo Html::link('voto/', 'Reportar Voto'); ?>

              </li>
              <li class="dropdown">
                <?php echo Html::link('#', 'Usuario<b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown" role="button"'); ?>
                    <ul class="dropdown-menu">
                      <li><?php echo Html::link('usuario/nuevo', 'Nuevo', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('usuario/', 'Listar', 'tabindex="-1"'); ?></li>
                    </ul>
              </li>
              <li class="">

                <?php echo Html::link('salir/', 'Salir'); ?>

              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</div>