<div class="container" id ="top">
    <div class="navbar  navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php echo Html::link('index', 'PSUV Falcón','class="brand"'); ?>
          <ul class="nav pull-right">
              <li>
                <?php echo Html::link('#', '<strong>'.Auth::get('usuario').'</strong>'); ?>
              </li>
          </ul>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">

             <?php echo Html::link('', 'Principal'); ?>
              </li>
              <li><?php echo Html::link('reporte/reportar', 'Reportar', 'tabindex="-1"'); ?></li>
              <?php if ( Auth::get('perfil') == 1 ) :?>
<!-- Reportes  de  Votacion -->
             <li class="dropdown">
                <?php echo Html::link('#', 'Reportes<b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown" role="button"'); ?>
                    <ul class="dropdown-menu">
                      <li><?php echo Html::link('reporte/', 'Reportes', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('reporte/', 'Reporte x Hora', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('reporte/', 'Reporte Oficial', 'tabindex="-1"'); ?></li>

                    </ul>
              </li>
              <?php endif; ?>

               <li class="">

                <?php echo Html::link('llamadas/', 'LLamadas'); ?>

              </li>
<!--  Operaciones de  Votos -->
              <li class="dropdown">
                <?php echo Html::link('#', 'Votos <b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown" role="button"'); ?>
                    <ul class="dropdown-menu">
                      <li><?php echo Html::link('voto/', 'Reportar Voto', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('voto/azul/', 'Reportar Voto Azul', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('buscar/', 'Consultar Voto', 'tabindex="-1"'); ?></li>
                    </ul>
              </li>
<!-- Área Administración -->
            <?php if ( Auth::get('perfil') == 1 ) :?>
              <li class="dropdown">
                <?php echo Html::link('#', 'Usuario<b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown" role="button"'); ?>
                    <ul class="dropdown-menu">
                      <li><?php echo Html::link('usuario/nuevo/', 'Nuevo', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('usuario/index/', 'Listar', 'tabindex="-1"'); ?></li>
                    </ul>
              </li>
            <?php endif; if ( Auth::get('nivel') == 0 ) :?>
              <li class="dropdown">
                <?php echo Html::link('#', 'Key Externos<b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown" role="button"'); ?>
                    <ul class="dropdown-menu">
                      <li><?php echo Html::link('key/nuevo/', 'Nuevo', 'tabindex="-1"'); ?></li>
                      <li><?php echo Html::link('key/', 'Listar', 'tabindex="-1"'); ?></li>
                    </ul>
              </li>
            <?php endif; ?>
              <li class="">

                <?php echo Html::link('salir/', 'Salir'); ?>

              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</div>