<div class="container">
    <div class="navbar  navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php echo Html::link('index', 'PSUVFACON','class="brand"'); ?>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">

             <?php echo Html::link('', 'Principal'); ?>
              </li>
              <li class="">

                 <?php echo Html::link('reporte/', 'Reportes'); ?>
              </li>
               <li class="">

                <?php echo Html::link('llamadas/', 'LLamadas'); ?>

              </li>
              <li class="pull_right">
                <?php echo Html::link('salir/', 'Salir'); ?>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</div>