


<div class="span10 offset1">

<table class="table table-stripped">
	<thead>
		<tr>
			<th>Centro de Votacion</th>
			<th>Cedula</th>
			<th>Nombre y Apellido</th>
			<th>Telefono</th>
			<th>Celular</th>
			<th>STATUS</th>

		</tr>
	</thead>
	<tbody>
	<?php

if($busqueda){
$estado = ($busqueda->voto)?'Activo':'Inactivo';
print "

		<tr>
			<td>$busqueda->centro_votacion</td>
			<td>$busqueda->cedula</td>
			<td>$busqueda->nombres   $busqueda->apellidos</td>
			<td>$busqueda->telefono</td>
			<td>$busqueda->celular</td>
 			<td class=\"text-center\">
 				<i class=\"icon-circle icon-large $estado \" title=\"Cambiar Estado\"></i>
 			</td>
		</tr>


";
}else{

	print "
		<tr>
			<td colspan =  \"6\">esta Vacia</td>


		</tr>

	";
}



	?>


</tbody>
</table>
<?php
echo Html::link("buscar/index/","<i class=\"icon-arrow-left\">Volver</i>");
?>

</div>